M48
; DRILL file {KiCad 8.0.6} date 2024-11-24T17:37:01-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-24T17:37:01-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X61.85Y-82.39
T2
X62.95Y-104.52
X125.13Y-89.89
X140.64Y-89.85
X156.67Y-89.58
M30
