M48
; DRILL file {KiCad 8.0.6} date 2024-11-16T13:19:45-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-16T13:19:45-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X61.85Y-82.39
T2
X62.73Y-103.34
X121.37Y-90.34
X138.09Y-90.1
X156.14Y-90.0
M30
